name: Generate NAP RSS

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "Update NAP feed [skip ci]"
            git push
          else
            echo "Nincs változás."
          fi
